global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  qsname: quickstart-datalake-47lining
  regions:
    - us-east-1
    - us-west-2
  reporting: true
tests:
  multi-node-without-demonstration:
    parameter_input: data-lake-without-demonstration-multi-node.json
    template_file: data-lake-master.template
    regions:
      - us-east-1
  single-node-with-wizard:
    parameter_input: data-lake-with-demonstration-single-node.json
    template_file: data-lake-master.template
    regions:
      - us-west-2
